### ISSUE TITLE
[problem] - Kcauldron[v.7] - No entity

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#31]
Related to the Forge <--> Bukkit Explosion prime events.

There is no Entity parsed with the event which makes Worldguard throw exceptions in the screen.

Tests: 
Industrial TNT: No event
Tiny TNT: No events
Nether ore: Event without entity

**Comment by enterprise12nx** [comment]
Yep was about to report this lol

**Comment by enterprise12nx** [comment]
[latest.txt](https://github.com/TCPR/KCauldron/files/105649/latest.txt)
[fml-server-latest.txt](https://github.com/TCPR/KCauldron/files/105650/fml-server-latest.txt)

**Comment by Robotia** [comment]
Ok I will look into this, thanks guys.

**Comment by Robotia** [comment]
@enterprise12nx and @KasperFranz , what do you think of a FakePlayer Entity named the name of the explosion type?

**Comment by enterprise12nx** [comment]
idk, i dont know programming well yet, whatever fixes things im fine with!

**Comment by Robotia** [comment]
@enterprise12nx Basically: Explosions would pretend to be players trying to break blocks at a location.

**Comment by enterprise12nx** [comment]
i mean i guess, something tells me that will interfere with something later down the line, especially with mods.

How come we cannot get it working like normal minecraft?

**Comment by Robotia** [comment]
@enterprise12nx It's because these are completely custom entities. An armed nether ore is basically a piece of TNT, but Bukkit doesn't know what an armed nether ore is, and never could. On that note, it might be better if I wrap it as a fake tnt entity.

**Comment by enterprise12nx** [comment]
ok, i leave it in your hands, i try to donate sometimes here and there since as far as i can see/find you guys are one of the last people maintaining kcauldron

**Comment by Robotia** [comment]
:smile:

**Comment by KasperFranz** [comment]
In the ExplosionPrime the entity for the normal TNT  is CraftTNTPrimed  you might be able to just ue that as the base for it?

**Comment by Robotia** [comment]
Yea that's what I was thinking of, I'll have to create a separate method for this.

**Comment by enterprise12nx** [comment]
Hope its out soon so i can get my public server going xD

**Comment by Robotia** [comment]
@enterprise12nx it'll be out in ~8 hours, sorry for the wait!

**Comment by enterprise12nx** [comment]
Ok sweet

**Comment by Robotia** [comment]
@enterprise12nx Please see build 8.

**Comment by enterprise12nx** [comment]
Having my players test it

**Comment by KasperFranz** [comment]
Build 8 still have this issue:

https://gist.github.com/KasperFranz/508ccca599ec80717e2b

**Comment by Robotia** [comment]
@KasperFranz @enterprise12nx Sorry I had left a residual Bukkit call in `newExplosion()`, which is now instead routed through Forge's `ExplosionEvent.Start`.

**Comment by enterprise12nx** [comment]
till getting Already Decorating! Error,  coulf 4you helo me fix it, ty!
[fml-server-latest.zip](https://github.com/TCPR/KCauldron/files/108576/fml-server-latest.zip)
[latest.zip](https://github.com/TCPR/KCauldron/files/108578/latest.zip)

**Comment by enterprise12nx** [comment]
@Robotia or is there some setting in cauldron i should change to fix this

**Comment by enterprise12nx** [comment]
worldgaurd still throws an error also 
[12:57:34] [Server thread/ERROR] [Minecraft/]: Could not pass event ExplosionPrimeEvent to WorldGuard v6.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.world.World.func_72885_a(World.java:3011) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1192) [mt.class:?]
	at powercrystals.netherores.entity.EntityArmedOre.explode(EntityArmedOre.java:94) [EntityArmedOre.class:?]
	at powercrystals.netherores.entity.EntityArmedOre.func_70071_h_(EntityArmedOre.java:74) [EntityArmedOre.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2670) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:875) [mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2619) [ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2424) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by KasperFranz** [comment]
It is fixed in build 9 which isn't public yet :)

**Comment by enterprise12nx** [comment]
Ok, any idea about the already decorating error?

**Comment by KasperFranz** [comment]
If the issue is closed then it is :)

**Comment by Robotia** [comment]
@enterprise12nx I see no error in the logs you have attached.

**Comment by enterprise12nx** [comment]
Prob wrong ones, these shud be right
[fml-server-latest.zip](https://github.com/TCPR/KCauldron/files/108965/fml-server-latest.zip)
[latest.zip](https://github.com/TCPR/KCauldron/files/108966/latest.zip)

**Comment by Robotia** [comment]
@enterprise12nx Can you make a [pastebin](https://pastebin.com)?

**Comment by enterprise12nx** [comment]
the files are to big for pastebin

**Comment by Robotia** [comment]
@enterprise12nx How frequently does this happen to you?

**Comment by enterprise12nx** [comment]
seems like it happens every 30 minutes, when ever i come back the servers down(2 hours?)

**Comment by Robotia** [comment]
@enterprise12nx And you never had this problem before using KC unofficial?

**Comment by enterprise12nx** [comment]
nope, but i can go test 1614.176 if you want

**Comment by Robotia** [comment]
@enterprise12nx That would be great, thanks.

**Comment by enterprise12nx** [comment]
@Robotia i am using worldborder to load chunks, its been up for some time now, no crashes or problems

**Comment by Robotia** [comment]
@enterprise12nx Alright, then I might've done something wrong :confused:

**Comment by enterprise12nx** [comment]
@Robotia np, your continuing something that was abandoned and not your code, its bound to me tricky and hard, i understand. Hopefully you can get it fixed, if you need something tested let me know, or if you want my world to test thats an option too, my modpack is public so.

**Comment by enterprise12nx** [comment]
@Robotia jobs plugin spams this 
http://pastebin.com/GqWvR81u

**Comment by Robotia** [comment]
There should be more lines in that exception, can you share the entire thing?

**Comment by enterprise12nx** [comment]
http://pastebin.com/15zr6ufi

**Comment by Robotia** [comment]
@enterprise12nx Will be fixed in R10.
